add car price + purchase validation
MarkLemashov/cars pull request #7
Opened 2020-10-27 13:49 UTC by MarkLemashov

2020-10-27 15:14 UTC, m-abramovich requested changes

2020-10-27 15:14 UTC, m-abramovich commented on cars/app/cars/models.py
> +        except Exception as error:
Exception is redundant here. 
You use exceptions on where you don't control flow fully. 
For example, when calling database, API of other services and so on. 
If the code is 100% your you know what you transmit as a parameter and what you do with it. Exception will never happen. 

You sae in DB right here. But DB library that you use already has this Exception. You don't need to wrap it up.

2020-10-27 15:14 UTC, m-abramovich commented on cars/app/cars/models.py
> +        self.money -= car.price
Use separate if-statement for the balance check. 
Raise if car.price is higher than the current balance value.

if something:
   raise something 
____

One important thing: use it in signal, not here

2020-10-27 15:14 UTC, m-abramovich commented on cars/app/cars/models.py
> +    price = models.IntegerField(default=0)
car never costs 0 money. This parameter should be mandatory.

2020-10-27 15:14 UTC, m-abramovich commented on cars/app/cars/models.py
> +        self.money += money_earned
What is the initial value of self.money?

2020-10-29 13:35 UTC, m-abramovich commented on cars/app/cars/models.py
> +            car.save()
```
else:
    raise RuntimeError('not enough money on the account')
```

2020-10-29 13:46 UTC, MarkLemashov commented on cars/app/cars/models.py
> +            car.save()
fixed.

2020-10-29 14:06 UTC, m-abramovich approved these changes

2020-10-29 14:06 UTC, merged